# -*- coding: utf-8 -*-
"""incidentAddrWithIncidentType.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mW9oD-kZfO49nWtojM29senQTRdpzLSO
"""

import numpy as np
import pandas as pd
import os
from google.colab import drive
drive.mount("/content/drive")

path = "/content/drive/Shared drives/DSCI HFD Team Fall 2021/datasets"

os.chdir(path)
os.listdir(path)

# load the data
incidentData = pd.read_csv(r"D2K Incident Data July 2018 to JAug 10 2021_Export.csv")
incidentData

# calculate the NaN in the column
incidentData["Basic Incident Full Address"].isna().sum()

incidentData["Basic Incident Type Code And Description (FD1.21)"].isna().sum()

non_nan_address = incidentData["Basic Incident Full Address"].dropna()
non_nan_firecode = incidentData["Basic Incident Type Code And Description (FD1.21)"].dropna()

# create a new dataframe to store the data
d = {'full address': non_nan_address, 'incident type': non_nan_firecode}
data = pd.DataFrame(data=d)

data

# delete the NaN in the data
data = data.dropna()

data.head()


# convert the dataframe to the excel form
os.chdir("/content/drive/Shared drives/DSCI HFD Team Fall 2021/results")

data.to_excel(r"incident data with incident type.xlsx")

path = "/content/drive/Shared drives/DSCI HFD Team Fall 2021/results"

os.chdir(path)
os.listdir(path)
