# -*- coding: utf-8 -*-
"""violationGroupByMonth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kc9xHpjHzoq6ztGa6RlOuHHdyS3fqmRn
"""

import numpy as np
import pandas as pd
import os
from google.colab import drive
drive.mount("/content/drive")

path = "/content/drive/Shared drives/DSCI HFD Team Fall 2021/results"

os.chdir(path)
os.listdir(path)

MonthData = pd.read_excel(r"Address_&_Violation_Records_data 2020&2021_full_address.xlsx")
MonthData.head()

import datetime as dt
MonthGroupBy = pd.to_datetime(MonthData["RESULTDTTM"])
res = MonthGroupBy.groupby([MonthGroupBy.dt.year, MonthGroupBy.dt.month])

res

# res.agg("count")
res = res.agg("count")
res.plot(kind="bar")

res.plot(kind="bar",)

